# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /mnt/bitbake_ext4/src/poky/meta \
  /mnt/bitbake_ext4/src/poky/meta-poky \
  /mnt/bitbake_ext4/src/poky/meta-yocto-bsp \
  /mnt/bitbake_ext4/src/meta-openembedded/meta-oe \
  /mnt/bitbake_ext4/src/meta-raspberrypi \
  /mnt/bitbake_ext4/src/esme-3s12/meta-esme-images \
  "
